language: python
python:
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U conan
  - pip install codecov
  - pip install scipy
  - pip install pytest-cov
  - export PYPHYSX_COV=true
install:
  - python setup.py build
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/build/lib.linux-x86_64-$TRAVIS_PYTHON_VERSION
  - cd build/temp.linux-x86_64-$TRAVIS_PYTHON_VERSION
  - pytest tests --cov=codecov
  - make gcov
after_success:
  - codecov -X gcov
  - codecov
